version: "3.9"
services:
  postgres12:
    image: postgres:12-alpine
    environment:
    - POSTGRES_PASSWORD=password
    - POSTGRES_DB=db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "db", "-U", "postgres" ]
      timeout: 45s
      interval: 20s
      retries: 5
    deploy:
      restart_policy:
        condition: on-failure
  frontend:
    image: m2tx/neowaytc-frontend:0.0.3
    healthcheck:
      test: "service nginx status || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 15s
    ports:
      - 80:80
    deploy:
      restart_policy:
        condition: on-failure
  backendgo:
    image: m2tx/neowaytc-backendgo:0.0.2
    healthcheck:
      test: "curl --fail --silent http://localhost:8081/health | grep UP || exit 1"
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 30s
    environment:
      - "DB_URL=postgres://postgres:password@postgres12:5432/db"
      - "MODE=release"
    ports:
      - 8081:8081
    depends_on:
      - "postgres12"
    deploy:
      restart_policy:
        condition: on-failure
